language: node_js
node_js:
  - 14
#Permette a travis di cachare tra una build e l'altra per essere più veloce
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
script:
  #- npm test
  - npm run build