/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",  // Modificare con la chiave che si trova su AWS
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_XXXXXXXXX", // Modificare con la chiave che si trova su AWS
    "aws_user_pools_web_client_id": "XXXXXXXXXXXXXXXXXXXXXXXXXX", // Modificare con la chiave che si trova su AWS
    "oauth": {}
};

export default awsmobile;
