version: "3.8"
services:
  eml-fe:
    container_name: "eml-fe"
    image: "eml-fe:latest"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .src/pages:/app/pages
      - .src/public:/app/public
      - .src/components:/app/components
      - .src/styles:/app/styles
